/**
 * PET911 TRAINING SYSTEM - Part 2: Module Content Definitions
 * 
 * Detailed module content for:
 * - Volunteer Orientation
 * - Transporter Training
 * - Foster Training
 */

import type { TrainingModule, Assessment } from './types';
import { MODULE_IDS } from './types';
import type { RoleId } from '../roles';

// ═══════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════

function createAssessment(
  moduleId: string,
  title: string,
  questionCount: number,
  passingScore: number,
  timeLimitMinutes: number,
  proctored: boolean = false
): Assessment {
  return {
    id: `assess_${moduleId}`,
    moduleId,
    title,
    description: `Final assessment for ${title}`,
    instructions: `You must score ${passingScore}% or higher to pass. You have 3 attempts.`,
    questions: [],
    totalPoints: questionCount * 2,
    passingScore,
    passingPoints: Math.ceil((questionCount * 2 * passingScore) / 100),
    timeLimitMinutes,
    allowRetake: true,
    maxAttempts: 3,
    retakeWaitHours: proctored ? 48 : 24,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResults: 'AFTER_SUBMISSION',
    proctored,
  };
}

// ═══════════════════════════════════════════════════════════════════
// VOLUNTEER ORIENTATION MODULE
// ═══════════════════════════════════════════════════════════════════

export const MODULE_VOLUNTEER_ORIENTATION: TrainingModule = {
  id: MODULE_IDS.VOLUNTEER_ORIENTATION,
  code: 'VOL-101',
  title: 'Volunteer Orientation',
  shortDescription: 'Introduction to PetMayday and your role as a volunteer',
  fullDescription: `
    Welcome to PetMayday! This orientation module introduces you to our mission,
    values, and the important work we do reuniting lost pets with their families.
    You'll learn about our organization structure, how to use our platform,
    and the expectations we have for all volunteers.
  `,
  version: '2.0',
  effectiveDate: '2026-01-01T00:00:00Z',
  category: 'ORIENTATION',
  difficulty: 'BEGINNER',
  targetRoles: ['community_volunteer', 'transporter', 'foster', 'emergency_foster', 'trapper', 'junior_moderator', 'moderator', 'lead_moderator'],
  prerequisites: [],
  corequisites: [],

  lessons: [
    {
      id: 'les_vol101_1',
      moduleId: MODULE_IDS.VOLUNTEER_ORIENTATION,
      orderIndex: 1,
      title: 'Welcome to PetMayday',
      description: 'Learn about our mission, history, and impact',
      learningObjectives: [
        { id: 'obj_v1_1', description: 'Explain the mission and vision of PetMayday', measurable: true, assessedInQuiz: true },
        { id: 'obj_v1_2', description: 'Describe the scope of the lost pet problem in the US', measurable: true, assessedInQuiz: true },
        { id: 'obj_v1_3', description: 'Identify key stakeholders in our ecosystem', measurable: true, assessedInQuiz: false },
      ],
      content: [
        {
          id: 'cnt_v1_1',
          type: 'VIDEO',
          title: 'Our Mission: Reuniting Pets with Families',
          description: 'A heartwarming introduction to what we do and why it matters',
          durationMinutes: 8,
          contentUrl: '/helpers/training/vol101/mission',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v1_2',
          type: 'READING',
          title: 'The Lost Pet Crisis',
          description: 'Statistics and facts about lost pets in America',
          durationMinutes: 10,
          contentUrl: '/helpers/training/vol101/lost-pet-crisis',
          downloadable: true,
          downloadUrl: '/training/docs/vol101/lost-pet-crisis.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v1_3',
          type: 'VIDEO',
          title: 'Success Stories',
          description: 'Real reunification stories from our volunteers',
          durationMinutes: 12,
          contentUrl: '/helpers/training/vol101/success-stories',
          downloadable: false,
          requiredForCompletion: false,
        },
      ],
      estimatedDurationMinutes: 30,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_v1',
        questions: [
          {
            id: 'q_v1_1',
            type: 'MULTIPLE_CHOICE',
            question: 'What is the primary mission of PetMayday?',
            options: [
              { id: 'a', text: 'To rescue stray animals', isCorrect: false, feedback: 'While we help strays, our primary mission is reunification.' },
              { id: 'b', text: 'To reunite lost pets with their families', isCorrect: true, feedback: 'Correct! Reunification is our core mission.' },
              { id: 'c', text: 'To provide veterinary care', isCorrect: false },
              { id: 'd', text: 'To adopt out homeless pets', isCorrect: false },
            ],
            points: 1,
            explanation: "PetMayday's primary mission is to reunite lost pets with their families through community coordination and technology.",
            objectiveId: 'obj_v1_1',
            tags: ['mission', 'basics'],
            difficulty: 'BEGINNER',
          },
          {
            id: 'q_v1_2',
            type: 'MULTIPLE_CHOICE',
            question: 'Approximately how many pets go missing in the US each year?',
            options: [
              { id: 'a', text: '1 million', isCorrect: false },
              { id: 'b', text: '5 million', isCorrect: false },
              { id: 'c', text: '10 million', isCorrect: true },
              { id: 'd', text: '20 million', isCorrect: false },
            ],
            points: 1,
            explanation: 'Studies estimate approximately 10 million pets go missing in the US each year.',
            objectiveId: 'obj_v1_2',
            tags: ['statistics'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_vol101_2',
      moduleId: MODULE_IDS.VOLUNTEER_ORIENTATION,
      orderIndex: 2,
      title: 'How PetMayday Works',
      description: 'Understanding our platform, processes, and your role',
      learningObjectives: [
        { id: 'obj_v2_1', description: 'Navigate the PetMayday platform and mobile app', measurable: true, assessedInQuiz: true },
        { id: 'obj_v2_2', description: 'Explain the case lifecycle from report to resolution', measurable: true, assessedInQuiz: true },
        { id: 'obj_v2_3', description: 'Identify different volunteer roles and responsibilities', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_v2_1',
          type: 'VIDEO',
          title: 'Platform Overview',
          description: 'Tour of the PetMayday website and mobile app',
          durationMinutes: 15,
          contentUrl: '/helpers/training/vol101/platform-tour',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v2_2',
          type: 'INTERACTIVE',
          title: 'Interactive Platform Walkthrough',
          description: 'Hands-on practice navigating key features',
          durationMinutes: 20,
          contentUrl: '/helpers/training/vol101/platform-walkthrough',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v2_3',
          type: 'READING',
          title: 'Case Lifecycle Guide',
          description: 'Detailed explanation of how cases move through our system',
          durationMinutes: 10,
          contentUrl: '/helpers/training/vol101/case-lifecycle',
          downloadable: true,
          downloadUrl: '/training/docs/vol101/case-lifecycle.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v2_4',
          type: 'VIDEO',
          title: 'Volunteer Roles Explained',
          description: 'Overview of all volunteer positions',
          durationMinutes: 10,
          contentUrl: '/helpers/training/vol101/volunteer-roles',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 55,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_v2',
        questions: [
          {
            id: 'q_v2_1',
            type: 'ORDERING',
            question: 'Put the case lifecycle stages in the correct order:',
            correctAnswer: ['Report Filed', 'Case Verified', 'Match Identified', 'Verification Requested', 'Pet Reunited', 'Case Closed'],
            points: 2,
            explanation: 'Cases progress through verification, matching, and reunification stages.',
            objectiveId: 'obj_v2_2',
            tags: ['case-lifecycle'],
            difficulty: 'BEGINNER',
          },
          {
            id: 'q_v2_2',
            type: 'MATCHING',
            question: 'Match each volunteer role with its primary responsibility:',
            matchingPairs: [
              { left: 'Transporter', right: 'Moving pets between locations' },
              { left: 'Foster', right: 'Temporary home for found pets' },
              { left: 'Trapper', right: 'Safely capturing stray/feral cats' },
              { left: 'Moderator', right: 'Verifying cases and matches' },
            ],
            points: 2,
            explanation: 'Each volunteer role has specific responsibilities.',
            objectiveId: 'obj_v2_3',
            tags: ['roles'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 75,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_vol101_3',
      moduleId: MODULE_IDS.VOLUNTEER_ORIENTATION,
      orderIndex: 3,
      title: 'Code of Conduct & Safety',
      description: 'Understanding expectations, boundaries, and staying safe',
      learningObjectives: [
        { id: 'obj_v3_1', description: 'Recite core principles of the PetMayday Code of Conduct', measurable: true, assessedInQuiz: true },
        { id: 'obj_v3_2', description: 'Identify situations requiring escalation to a moderator', measurable: true, assessedInQuiz: true },
        { id: 'obj_v3_3', description: 'Apply personal safety protocols', measurable: true, assessedInQuiz: true },
        { id: 'obj_v3_4', description: 'Explain mandatory reporting obligations', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_v3_1',
          type: 'VIDEO',
          title: 'Our Code of Conduct',
          description: 'Values and principles guiding our volunteer community',
          durationMinutes: 12,
          contentUrl: '/helpers/training/vol101/code-of-conduct',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v3_2',
          type: 'READING',
          title: 'Code of Conduct Full Document',
          description: 'Complete code of conduct for reference',
          durationMinutes: 15,
          contentUrl: '/helpers/training/vol101/code-of-conduct-full',
          downloadable: true,
          downloadUrl: '/training/docs/vol101/code-of-conduct-full.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v3_3',
          type: 'VIDEO',
          title: 'Personal Safety for Volunteers',
          description: 'How to stay safe during volunteer activities',
          durationMinutes: 15,
          contentUrl: '/helpers/training/vol101/personal-safety',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v3_4',
          type: 'SCENARIO',
          title: 'Safety Scenarios',
          description: 'Interactive scenarios to practice safety decision-making',
          durationMinutes: 15,
          contentUrl: '/helpers/training/vol101/safety-scenarios',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v3_5',
          type: 'READING',
          title: 'Mandatory Reporting Guidelines',
          description: 'When and how to report animal abuse, neglect, or dangerous situations',
          durationMinutes: 10,
          contentUrl: '/helpers/training/vol101/mandatory-reporting',
          downloadable: true,
          downloadUrl: '/training/docs/vol101/mandatory-reporting.pdf',
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 67,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_v3',
        questions: [
          {
            id: 'q_v3_1',
            type: 'MULTIPLE_SELECT',
            question: 'Which are core principles in the PetMayday Code of Conduct? (Select all)',
            options: [
              { id: 'a', text: 'Animal welfare comes first', isCorrect: true },
              { id: 'b', text: 'Maximize profits', isCorrect: false },
              { id: 'c', text: 'Respect and professionalism', isCorrect: true },
              { id: 'd', text: 'Transparency and honesty', isCorrect: true },
              { id: 'e', text: 'Work alone whenever possible', isCorrect: false },
            ],
            points: 2,
            explanation: 'Core principles focus on animal welfare, respect, and transparency.',
            objectiveId: 'obj_v3_1',
            tags: ['code-of-conduct'],
            difficulty: 'BEGINNER',
          },
          {
            id: 'q_v3_2',
            type: 'SCENARIO_BASED',
            question: 'You arrive at a pickup location and the person seems aggressive. What should you do?',
            context: 'You are a transporter and the finder is upset and raising their voice.',
            options: [
              { id: 'a', text: 'Argue back to defend yourself', isCorrect: false },
              { id: 'b', text: 'Stay calm, apologize for inconvenience, proceed if safe', isCorrect: true },
              { id: 'c', text: 'Leave immediately without the cat', isCorrect: false },
              { id: 'd', text: 'Call the police', isCorrect: false },
            ],
            points: 2,
            explanation: 'De-escalation is the first approach. Only disengage if truly unsafe.',
            objectiveId: 'obj_v3_3',
            tags: ['safety', 'de-escalation'],
            difficulty: 'INTERMEDIATE',
          },
          {
            id: 'q_v3_3',
            type: 'TRUE_FALSE',
            question: 'If you suspect animal abuse, you should wait to gather evidence before reporting.',
            options: [
              { id: 'true', text: 'True', isCorrect: false },
              { id: 'false', text: 'False', isCorrect: true },
            ],
            points: 1,
            explanation: 'Report immediately. Evidence gathering is for authorities.',
            objectiveId: 'obj_v3_4',
            tags: ['mandatory-reporting'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_vol101_4',
      moduleId: MODULE_IDS.VOLUNTEER_ORIENTATION,
      orderIndex: 4,
      title: 'Communication Best Practices',
      description: 'Effective communication with pet owners, finders, and team',
      learningObjectives: [
        { id: 'obj_v4_1', description: 'Apply empathetic communication with distressed pet owners', measurable: true, assessedInQuiz: true },
        { id: 'obj_v4_2', description: 'Use appropriate channels for different communications', measurable: true, assessedInQuiz: true },
        { id: 'obj_v4_3', description: 'Maintain professional boundaries', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_v4_1',
          type: 'VIDEO',
          title: 'Empathetic Communication',
          description: 'Connecting with people experiencing the stress of a lost pet',
          durationMinutes: 12,
          contentUrl: '/helpers/training/vol101/empathetic-communication',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v4_2',
          type: 'READING',
          title: 'Communication Templates & Guidelines',
          description: 'Standard messages and best practices',
          durationMinutes: 15,
          contentUrl: '/helpers/training/vol101/communication-templates',
          downloadable: true,
          downloadUrl: '/training/docs/vol101/communication-templates.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_v4_3',
          type: 'SCENARIO',
          title: 'Difficult Conversations Practice',
          description: 'Interactive scenarios for challenging situations',
          durationMinutes: 20,
          contentUrl: '/helpers/training/vol101/difficult-conversations',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 47,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_v4',
        questions: [
          {
            id: 'q_v4_1',
            type: 'SCENARIO_BASED',
            question: 'A pet owner messages you at 11 PM in a panic. How do you respond?',
            context: 'Their dog just escaped and they are very upset.',
            options: [
              { id: 'a', text: 'Ignore until morning', isCorrect: false },
              { id: 'b', text: 'Give your personal phone number', isCorrect: false },
              { id: 'c', text: 'Acknowledge, provide guidance, set expectations', isCorrect: true },
              { id: 'd', text: 'Tell them to calm down', isCorrect: false },
            ],
            points: 2,
            explanation: 'Acknowledge promptly with empathy while maintaining boundaries.',
            objectiveId: 'obj_v4_1',
            tags: ['communication', 'empathy'],
            difficulty: 'INTERMEDIATE',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
  ],

  finalAssessment: createAssessment(
    MODULE_IDS.VOLUNTEER_ORIENTATION,
    'Volunteer Orientation Final Assessment',
    15,
    80,
    30
  ),

  estimatedDurationMinutes: 199,
  completionDeadlineDays: 14,
  grantsCertification: true,
  certificationId: 'cert_volunteer_orientation',
  certificationValidityMonths: 24,
  ceCredits: 3,
  ceCategory: 'ORIENTATION',
  author: 'PetMayday Training Team',
  reviewedBy: 'Training Committee',
  lastReviewedAt: '2026-01-01T00:00:00Z',
  nextReviewDue: '2027-01-01T00:00:00Z',
  tags: ['orientation', 'basics', 'required'],
  status: 'ACTIVE',
};

const MODERATOR_TARGET_ROLES: RoleId[] = ['junior_moderator', 'moderator', 'lead_moderator'];

const MODERATOR_MODULE_COMMON: Pick<
  TrainingModule,
  | 'version'
  | 'effectiveDate'
  | 'category'
  | 'difficulty'
  | 'targetRoles'
  | 'prerequisites'
  | 'corequisites'
  | 'estimatedDurationMinutes'
  | 'completionDeadlineDays'
  | 'grantsCertification'
  | 'certificationId'
  | 'certificationValidityMonths'
  | 'ceCredits'
  | 'ceCategory'
  | 'author'
  | 'reviewedBy'
  | 'lastReviewedAt'
  | 'nextReviewDue'
  | 'tags'
  | 'status'
> = {
  version: '1.0',
  effectiveDate: '2026-01-01T00:00:00Z',
  category: 'ROLE_SPECIFIC',
  difficulty: 'INTERMEDIATE',
  targetRoles: MODERATOR_TARGET_ROLES,
  prerequisites: [MODULE_IDS.VOLUNTEER_ORIENTATION],
  corequisites: [],
  estimatedDurationMinutes: 60,
  completionDeadlineDays: 14,
  grantsCertification: false,
  certificationId: undefined,
  certificationValidityMonths: undefined,
  ceCredits: 1,
  ceCategory: 'ROLE_SPECIFIC',
  author: 'PetMayday Governance',
  reviewedBy: 'Lead Moderator',
  lastReviewedAt: '2026-01-01T00:00:00Z',
  nextReviewDue: '2027-01-01T00:00:00Z',
  tags: ['moderator', 'required'],
  status: 'ACTIVE',
};

export const MODULE_MODERATOR_BASICS: TrainingModule = {
  id: MODULE_IDS.MODERATOR_BASICS,
  code: 'MOD-101',
  title: 'Moderator Basics',
  shortDescription: 'Core rules, safety, privacy, and how to operate as a PetMayday moderator',
  fullDescription: `
    This module introduces the non-negotiable rules and operating principles for moderators.
    Focus: privacy, evidence standards, documentation, and escalation.
  `,
  ...MODERATOR_MODULE_COMMON,
  lessons: [
    {
      id: 'les_mod101_1',
      moduleId: MODULE_IDS.MODERATOR_BASICS,
      orderIndex: 1,
      title: 'Rules of the Road (Court-Safe Operations)',
      description: 'What you can and cannot do, and why the audit trail matters',
      learningObjectives: [],
      content: [
        {
          id: 'cnt_mod101_1',
          type: 'READING',
          title: 'Moderator Code of Conduct',
          description: 'Read and internalize the code of conduct and enforcement outcomes',
          durationMinutes: 20,
          contentUrl: '/helpers/training/mod101/code-of-conduct',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 20,
      requiredForModuleCompletion: true,
    },
  ],
  finalAssessment: createAssessment(MODULE_IDS.MODERATOR_BASICS, 'Moderator Basics', 10, 80, 20, false),
};

export const MODULE_CASE_TRIAGE: TrainingModule = {
  id: MODULE_IDS.CASE_TRIAGE,
  code: 'MOD-110',
  title: 'Case Triage',
  shortDescription: 'How to triage new cases quickly and safely using SOPs',
  fullDescription: `
    Learn the initial triage workflow: completeness checks, urgency signals, and escalation.
  `,
  ...MODERATOR_MODULE_COMMON,
  lessons: [
    {
      id: 'les_mod110_1',
      moduleId: MODULE_IDS.CASE_TRIAGE,
      orderIndex: 1,
      title: 'Triage Workflow',
      description: 'Step-by-step triage checklist and documentation requirements',
      learningObjectives: [],
      content: [
        {
          id: 'cnt_mod110_1',
          type: 'READING',
          title: 'SOP: New Case Triage',
          description: 'Follow the SOP and practice applying it consistently',
          durationMinutes: 25,
          contentUrl: '/helpers/training/mod110/case-triage',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 25,
      requiredForModuleCompletion: true,
    },
  ],
  finalAssessment: createAssessment(MODULE_IDS.CASE_TRIAGE, 'Case Triage', 10, 80, 20, false),
};

export const MODULE_MATCH_VERIFICATION: TrainingModule = {
  id: MODULE_IDS.MATCH_VERIFICATION,
  code: 'MOD-120',
  title: 'Match Verification',
  shortDescription: 'Verify matches before contact release—no false hope, no harm',
  fullDescription: `
    Learn evidence standards, photo checks, timing, and safe contact release.
  `,
  ...MODERATOR_MODULE_COMMON,
  lessons: [
    {
      id: 'les_mod120_1',
      moduleId: MODULE_IDS.MATCH_VERIFICATION,
      orderIndex: 1,
      title: 'Verification Standards',
      description: 'Evidence thresholds and escalation conditions',
      learningObjectives: [],
      content: [
        {
          id: 'cnt_mod120_1',
          type: 'READING',
          title: 'SOP: Match Verification',
          description: 'Apply the verification SOP and document the decision path',
          durationMinutes: 25,
          contentUrl: '/helpers/training/mod120/match-verification',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 25,
      requiredForModuleCompletion: true,
    },
  ],
  finalAssessment: createAssessment(MODULE_IDS.MATCH_VERIFICATION, 'Match Verification', 10, 80, 20, false),
};

// ═══════════════════════════════════════════════════════════════════
// TRANSPORT TRAINING MODULES
// ═══════════════════════════════════════════════════════════════════

export const MODULE_TRANSPORT_BASICS: TrainingModule = {
  id: MODULE_IDS.TRANSPORT_BASICS,
  code: 'TRN-101',
  title: 'Transport Basics',
  shortDescription: 'Foundational training for pet transporters',
  fullDescription: `
    This module covers essential knowledge and skills for safely transporting pets.
    You'll learn about vehicle preparation, animal handling, documentation,
    and emergency procedures.
  `,
  version: '1.5',
  effectiveDate: '2026-01-01T00:00:00Z',
  category: 'ROLE_SPECIFIC',
  difficulty: 'BEGINNER',
  targetRoles: ['transporter', 'senior_transporter'],
  prerequisites: [MODULE_IDS.VOLUNTEER_ORIENTATION],
  corequisites: [],

  lessons: [
    {
      id: 'les_trn101_1',
      moduleId: MODULE_IDS.TRANSPORT_BASICS,
      orderIndex: 1,
      title: 'Vehicle Preparation & Safety',
      description: 'Preparing your vehicle for safe pet transport',
      learningObjectives: [
        { id: 'obj_t1_1', description: 'Prepare a vehicle for safe pet transport', measurable: true, assessedInQuiz: true },
        { id: 'obj_t1_2', description: 'Identify required equipment for transport', measurable: true, assessedInQuiz: true },
        { id: 'obj_t1_3', description: 'Perform a pre-transport safety check', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_t1_1',
          type: 'VIDEO',
          title: 'Vehicle Setup for Pet Transport',
          description: 'How to prepare your car for safe, comfortable pet transport',
          durationMinutes: 15,
          contentUrl: '/helpers/training/trn101/vehicle-setup',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t1_2',
          type: 'READING',
          title: 'Transport Equipment Checklist',
          description: 'Complete list of required and recommended equipment',
          durationMinutes: 10,
          contentUrl: '/helpers/training/trn101/equipment-checklist',
          downloadable: true,
          downloadUrl: '/training/docs/trn101/equipment-checklist.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t1_3',
          type: 'INTERACTIVE',
          title: 'Pre-Transport Checklist Simulator',
          description: 'Practice completing the pre-transport safety check',
          durationMinutes: 10,
          contentUrl: '/helpers/training/trn101/pretransport-check',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 35,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_t1',
        questions: [
          {
            id: 'q_t1_1',
            type: 'MULTIPLE_SELECT',
            question: 'Which items are REQUIRED for every transport? (Select all)',
            options: [
              { id: 'a', text: 'Secure carrier or crate', isCorrect: true },
              { id: 'b', text: 'Leash and slip lead', isCorrect: true },
              { id: 'c', text: 'Treats', isCorrect: false },
              { id: 'd', text: 'First aid kit', isCorrect: true },
              { id: 'e', text: 'Water and bowl', isCorrect: true },
              { id: 'f', text: 'GPS tracker', isCorrect: false },
            ],
            points: 2,
            explanation: 'Required items ensure safety and preparedness.',
            objectiveId: 'obj_t1_2',
            tags: ['equipment', 'preparation'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_trn101_2',
      moduleId: MODULE_IDS.TRANSPORT_BASICS,
      orderIndex: 2,
      title: 'Pickup & Handoff Procedures',
      description: 'Safe and documented pet pickup and delivery',
      learningObjectives: [
        { id: 'obj_t2_1', description: 'Execute a safe pet pickup procedure', measurable: true, assessedInQuiz: true },
        { id: 'obj_t2_2', description: 'Complete required documentation', measurable: true, assessedInQuiz: true },
        { id: 'obj_t2_3', description: 'Verify pet identity using photos', measurable: true, assessedInQuiz: true },
        { id: 'obj_t2_4', description: 'Handle common pickup challenges', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_t2_1',
          type: 'VIDEO',
          title: 'The Pickup Process',
          description: 'Step-by-step guide to picking up a pet safely',
          durationMinutes: 12,
          contentUrl: '/helpers/training/trn101/pickup-process',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t2_2',
          type: 'VIDEO',
          title: 'Documentation & Verification',
          description: 'How to document the pet and verify identity',
          durationMinutes: 10,
          contentUrl: '/helpers/training/trn101/documentation',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t2_3',
          type: 'SCENARIO',
          title: 'Pickup Scenario Practice',
          description: 'Interactive scenarios for common and challenging pickups',
          durationMinutes: 20,
          contentUrl: '/training/interactive/trn101/pickup-scenarios',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t2_4',
          type: 'READING',
          title: 'Transport Documentation Forms',
          description: 'All forms and how to complete them',
          durationMinutes: 10,
          contentUrl: '/training/docs/trn101/transport-forms.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/trn101/transport-forms.pdf',
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 52,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_t2',
        questions: [
          {
            id: 'q_t2_1',
            type: 'ORDERING',
            question: 'Put the pickup steps in correct order:',
            correctAnswer: [
              'Confirm pickup details in app',
              'Arrive and contact finder',
              'Verify pet against photos',
              'Complete condition checklist',
              'Secure pet in carrier',
              'Take departure photo',
              'Update status in app',
            ],
            points: 3,
            explanation: 'Following the correct sequence ensures safety and documentation.',
            objectiveId: 'obj_t2_1',
            tags: ['pickup', 'procedure'],
            difficulty: 'INTERMEDIATE',
          },
          {
            id: 'q_t2_2',
            type: 'SCENARIO_BASED',
            question: "The pet doesn't match the photos in the app. What do you do?",
            context: 'The cat is a different color than pictured.',
            options: [
              { id: 'a', text: 'Trust the finder and proceed', isCorrect: false },
              { id: 'b', text: 'Document discrepancy, escalate to moderator', isCorrect: true },
              { id: 'c', text: 'Refuse pickup and leave', isCorrect: false },
              { id: 'd', text: 'Take the cat anyway', isCorrect: false },
            ],
            points: 2,
            explanation: 'Document discrepancies and escalate. Never proceed with uncertainty.',
            objectiveId: 'obj_t2_3',
            tags: ['verification', 'escalation'],
            difficulty: 'INTERMEDIATE',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_trn101_3',
      moduleId: MODULE_IDS.TRANSPORT_BASICS,
      orderIndex: 3,
      title: 'Animal Behavior During Transport',
      description: 'Understanding and responding to pet behavior in transit',
      learningObjectives: [
        { id: 'obj_t3_1', description: 'Recognize signs of stress in cats and dogs', measurable: true, assessedInQuiz: true },
        { id: 'obj_t3_2', description: 'Apply calming techniques during transport', measurable: true, assessedInQuiz: true },
        { id: 'obj_t3_3', description: 'Identify when to stop and address needs', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_t3_1',
          type: 'VIDEO',
          title: 'Reading Animal Body Language',
          description: 'How to recognize stress, fear, and comfort',
          durationMinutes: 18,
          contentUrl: '/training/videos/trn101/body-language.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t3_2',
          type: 'VIDEO',
          title: 'Calming Techniques for Transport',
          description: 'Music, pheromones, and other calming strategies',
          durationMinutes: 12,
          contentUrl: '/training/videos/trn101/calming-techniques.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t3_3',
          type: 'READING',
          title: 'Species-Specific Transport Considerations',
          description: 'Different needs for cats, dogs, and other species',
          durationMinutes: 15,
          contentUrl: '/training/docs/trn101/species-specific.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/trn101/species-specific.pdf',
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 45,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_t3',
        questions: [
          {
            id: 'q_t3_1',
            type: 'MULTIPLE_SELECT',
            question: 'Which are signs of stress in a cat? (Select all)',
            options: [
              { id: 'a', text: 'Flattened ears', isCorrect: true },
              { id: 'b', text: 'Dilated pupils', isCorrect: true },
              { id: 'c', text: 'Relaxed slow blink', isCorrect: false },
              { id: 'd', text: 'Excessive vocalization', isCorrect: true },
              { id: 'e', text: 'Panting', isCorrect: true },
              { id: 'f', text: 'Tail up and relaxed', isCorrect: false },
            ],
            points: 2,
            explanation: 'Recognizing stress signs allows early intervention.',
            objectiveId: 'obj_t3_1',
            tags: ['body-language', 'cats', 'stress'],
            difficulty: 'INTERMEDIATE',
          },
          {
            id: 'q_t3_2',
            type: 'MULTIPLE_CHOICE',
            question: 'The dog is panting heavily and drooling. What should you do?',
            options: [
              { id: 'a', text: 'Keep driving - dogs pant normally', isCorrect: false },
              { id: 'b', text: 'Pull over, check temperature, offer water', isCorrect: true },
              { id: 'c', text: 'Turn up AC and keep driving', isCorrect: false },
              { id: 'd', text: 'Open the carrier to comfort the dog', isCorrect: false },
            ],
            points: 2,
            explanation: 'Heavy panting and drooling can indicate overheating. Pull over to assess.',
            objectiveId: 'obj_t3_3',
            tags: ['emergency', 'dogs', 'overheating'],
            difficulty: 'INTERMEDIATE',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_trn101_4',
      moduleId: MODULE_IDS.TRANSPORT_BASICS,
      orderIndex: 4,
      title: 'Emergency Procedures',
      description: 'Handling emergencies during transport',
      learningObjectives: [
        { id: 'obj_t4_1', description: 'Respond to a pet escape during transport', measurable: true, assessedInQuiz: true },
        { id: 'obj_t4_2', description: 'Administer basic first aid', measurable: true, assessedInQuiz: true },
        { id: 'obj_t4_3', description: 'Handle vehicle breakdown with pet onboard', measurable: true, assessedInQuiz: true },
        { id: 'obj_t4_4', description: 'Know when to go to emergency vet', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_t4_1',
          type: 'VIDEO',
          title: 'Pet Escape Prevention & Response',
          description: 'How to prevent escapes and what to do if one happens',
          durationMinutes: 15,
          contentUrl: '/training/videos/trn101/escape-response.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t4_2',
          type: 'VIDEO',
          title: 'Pet First Aid for Transporters',
          description: 'Basic first aid every transporter should know',
          durationMinutes: 20,
          contentUrl: '/training/videos/trn101/first-aid.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t4_3',
          type: 'READING',
          title: 'Emergency Protocol Quick Reference',
          description: 'Printable guide for emergency situations',
          durationMinutes: 10,
          contentUrl: '/training/docs/trn101/emergency-protocols.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/trn101/emergency-protocols.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_t4_4',
          type: 'SCENARIO',
          title: 'Emergency Scenario Training',
          description: 'Interactive emergency response practice',
          durationMinutes: 25,
          contentUrl: '/training/interactive/trn101/emergency-scenarios',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 70,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_t4',
        questions: [
          {
            id: 'q_t4_1',
            type: 'SCENARIO_BASED',
            question: 'While loading a cat, it escapes into nearby bushes. What is your FIRST action?',
            options: [
              { id: 'a', text: 'Run after the cat', isCorrect: false },
              { id: 'b', text: 'Stay calm, note location, report immediately', isCorrect: true },
              { id: 'c', text: 'Leave food out and wait', isCorrect: false },
              { id: 'd', text: 'Go buy a humane trap', isCorrect: false },
            ],
            points: 2,
            explanation: 'Report immediately and maintain visual contact if possible. Never chase.',
            objectiveId: 'obj_t4_1',
            tags: ['escape', 'emergency'],
            difficulty: 'INTERMEDIATE',
          },
          {
            id: 'q_t4_2',
            type: 'MULTIPLE_SELECT',
            question: 'Which situations require immediate emergency vet? (Select all)',
            options: [
              { id: 'a', text: 'Pet is unresponsive', isCorrect: true },
              { id: 'b', text: "Active bleeding that won't stop", isCorrect: true },
              { id: 'c', text: 'Pet is nervous and hiding', isCorrect: false },
              { id: 'd', text: 'Difficulty breathing', isCorrect: true },
              { id: 'e', text: 'Seizure activity', isCorrect: true },
              { id: 'f', text: 'Pet urinated in carrier', isCorrect: false },
            ],
            points: 3,
            explanation: 'Life-threatening emergencies require immediate vet care.',
            objectiveId: 'obj_t4_4',
            tags: ['emergency', 'veterinary'],
            difficulty: 'INTERMEDIATE',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
  ],

  finalAssessment: createAssessment(
    MODULE_IDS.TRANSPORT_BASICS,
    'Transport Basics Final Assessment',
    20,
    80,
    45
  ),

  estimatedDurationMinutes: 202,
  completionDeadlineDays: 21,
  grantsCertification: true,
  certificationId: 'cert_transport_basics',
  certificationValidityMonths: 24,
  ceCredits: 4,
  ceCategory: 'ROLE_SPECIFIC',
  author: 'PetMayday Training Team',
  reviewedBy: 'Senior Transport Coordinator',
  lastReviewedAt: '2026-01-01T00:00:00Z',
  nextReviewDue: '2027-01-01T00:00:00Z',
  tags: ['transport', 'required', 'vehicles', 'safety'],
  status: 'ACTIVE',
};

export const MODULE_FOSTER_BASICS: TrainingModule = {
  id: MODULE_IDS.FOSTER_BASICS,
  code: 'FST-101',
  title: 'Foster Basics',
  shortDescription: 'Foundational training for pet fosters',
  fullDescription: `
    Comprehensive module covering everything for temporary foster care.
    Learn about intake procedures, daily care, documentation, and
    when to seek help.
  `,
  version: '1.0',
  effectiveDate: '2026-01-01T00:00:00Z',
  category: 'ROLE_SPECIFIC',
  difficulty: 'BEGINNER',
  targetRoles: ['foster', 'emergency_foster'],
  prerequisites: [MODULE_IDS.VOLUNTEER_ORIENTATION],
  corequisites: [],

  lessons: [
    {
      id: 'les_fst101_1',
      moduleId: MODULE_IDS.FOSTER_BASICS,
      orderIndex: 1,
      title: 'Foster Intake Process',
      description: 'Receiving a foster pet into your home',
      learningObjectives: [
        { id: 'obj_f1_1', description: 'Complete foster intake documentation', measurable: true, assessedInQuiz: true },
        { id: 'obj_f1_2', description: 'Prepare a safe quarantine space', measurable: true, assessedInQuiz: true },
        { id: 'obj_f1_3', description: 'Conduct initial health assessment', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_f1_1',
          type: 'VIDEO',
          title: 'Preparing Your Home',
          description: 'Setting up a safe, comfortable space',
          durationMinutes: 15,
          contentUrl: '/training/videos/fst101/home-prep.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f1_2',
          type: 'VIDEO',
          title: 'The Intake Process',
          description: 'What to do when a foster pet arrives',
          durationMinutes: 12,
          contentUrl: '/training/videos/fst101/intake-process.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f1_3',
          type: 'READING',
          title: 'Foster Intake Checklist',
          description: 'Printable checklist for foster intake',
          durationMinutes: 10,
          contentUrl: '/training/docs/fst101/intake-checklist.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/fst101/intake-checklist.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f1_4',
          type: 'VIDEO',
          title: 'Initial Health Assessment',
          description: "How to check a foster pet's health",
          durationMinutes: 15,
          contentUrl: '/training/videos/fst101/health-assessment.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 52,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_f1',
        questions: [
          {
            id: 'q_f1_1',
            type: 'MULTIPLE_CHOICE',
            question: 'How long should a new foster be quarantined from your existing pets?',
            options: [
              { id: 'a', text: '24 hours', isCorrect: false },
              { id: 'b', text: '3-5 days', isCorrect: false },
              { id: 'c', text: '10-14 days minimum', isCorrect: true },
              { id: 'd', text: 'No quarantine needed', isCorrect: false },
            ],
            points: 2,
            explanation: '10-14 day quarantine allows monitoring for contagious diseases.',
            objectiveId: 'obj_f1_2',
            tags: ['quarantine', 'safety'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_fst101_2',
      moduleId: MODULE_IDS.FOSTER_BASICS,
      orderIndex: 2,
      title: 'Daily Care & Documentation',
      description: 'Providing excellent daily care and keeping records',
      learningObjectives: [
        { id: 'obj_f2_1', description: 'Meet daily care needs', measurable: true, assessedInQuiz: true },
        { id: 'obj_f2_2', description: 'Document daily observations', measurable: true, assessedInQuiz: true },
        { id: 'obj_f2_3', description: 'Recognize changes requiring attention', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_f2_1',
          type: 'VIDEO',
          title: 'Daily Care Routine',
          description: 'Feeding, water, litter, exercise, enrichment',
          durationMinutes: 18,
          contentUrl: '/training/videos/fst101/daily-care.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f2_2',
          type: 'READING',
          title: 'Foster Daily Log Guide',
          description: 'How to keep accurate daily records',
          durationMinutes: 10,
          contentUrl: '/training/docs/fst101/daily-log-guide.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/fst101/daily-log-guide.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f2_3',
          type: 'INTERACTIVE',
          title: 'Using the Foster App',
          description: 'Hands-on practice with foster tracking',
          durationMinutes: 15,
          contentUrl: '/training/interactive/fst101/foster-app',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 43,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_f2',
        questions: [
          {
            id: 'q_f2_1',
            type: 'MULTIPLE_SELECT',
            question: 'What should you document daily? (Select all)',
            options: [
              { id: 'a', text: 'Food and water intake', isCorrect: true },
              { id: 'b', text: 'Litter box usage', isCorrect: true },
              { id: 'c', text: 'Behavior and activity level', isCorrect: true },
              { id: 'd', text: 'Weather outside', isCorrect: false },
              { id: 'e', text: 'Any health concerns', isCorrect: true },
            ],
            points: 2,
            explanation: 'Daily documentation helps track health and detect issues early.',
            objectiveId: 'obj_f2_2',
            tags: ['documentation'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_fst101_3',
      moduleId: MODULE_IDS.FOSTER_BASICS,
      orderIndex: 3,
      title: 'Isolation & Existing Pets',
      description: 'Protecting your existing pets and the foster',
      learningObjectives: [
        { id: 'obj_f3_1', description: 'Implement proper quarantine protocols', measurable: true, assessedInQuiz: true },
        { id: 'obj_f3_2', description: 'Prevent disease transmission', measurable: true, assessedInQuiz: true },
        { id: 'obj_f3_3', description: 'Make safe introduction decisions', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_f3_1',
          type: 'VIDEO',
          title: 'Quarantine Essentials',
          description: 'Why quarantine matters and how to do it right',
          durationMinutes: 15,
          contentUrl: '/training/videos/fst101/quarantine.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f3_2',
          type: 'READING',
          title: 'Disease Prevention Guide',
          description: 'Common diseases and prevention',
          durationMinutes: 15,
          contentUrl: '/training/docs/fst101/disease-prevention.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/fst101/disease-prevention.pdf',
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 30,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_f3',
        questions: [
          {
            id: 'q_f3_1',
            type: 'MULTIPLE_SELECT',
            question: 'Which practices prevent disease transmission? (Select all)',
            options: [
              { id: 'a', text: 'Separate food/water bowls', isCorrect: true },
              { id: 'b', text: 'Wash hands between handling', isCorrect: true },
              { id: 'c', text: 'Dedicated litter box', isCorrect: true },
              { id: 'd', text: 'Share toys to socialize', isCorrect: false },
              { id: 'e', text: 'Change clothes after handling', isCorrect: true },
            ],
            points: 2,
            explanation: 'Strict separation and hygiene prevent disease spread.',
            objectiveId: 'obj_f3_2',
            tags: ['quarantine', 'disease'],
            difficulty: 'BEGINNER',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
    {
      id: 'les_fst101_4',
      moduleId: MODULE_IDS.FOSTER_BASICS,
      orderIndex: 4,
      title: 'When to Escalate',
      description: 'Recognizing problems and getting help',
      learningObjectives: [
        { id: 'obj_f4_1', description: 'Identify health issues requiring vet attention', measurable: true, assessedInQuiz: true },
        { id: 'obj_f4_2', description: 'Recognize behavioral concerns', measurable: true, assessedInQuiz: true },
        { id: 'obj_f4_3', description: 'Use proper channels for assistance', measurable: true, assessedInQuiz: true },
      ],
      content: [
        {
          id: 'cnt_f4_1',
          type: 'VIDEO',
          title: 'Health Red Flags',
          description: 'Signs that something is wrong',
          durationMinutes: 18,
          contentUrl: '/training/videos/fst101/health-red-flags.mp4',
          downloadable: false,
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f4_2',
          type: 'READING',
          title: 'Escalation Guide',
          description: 'When and how to escalate concerns',
          durationMinutes: 10,
          contentUrl: '/training/docs/fst101/escalation-guide.pdf',
          downloadable: true,
          downloadUrl: '/training/docs/fst101/escalation-guide.pdf',
          requiredForCompletion: true,
        },
        {
          id: 'cnt_f4_3',
          type: 'SCENARIO',
          title: 'Escalation Scenarios',
          description: 'Practice identifying when to escalate',
          durationMinutes: 15,
          contentUrl: '/training/interactive/fst101/escalation-scenarios',
          downloadable: false,
          requiredForCompletion: true,
        },
      ],
      estimatedDurationMinutes: 43,
      requiredForModuleCompletion: true,
      knowledgeCheck: {
        id: 'kc_f4',
        questions: [
          {
            id: 'q_f4_1',
            type: 'MULTIPLE_SELECT',
            question: 'Which require immediate vet attention? (Select all)',
            options: [
              { id: 'a', text: 'Not eating for 24+ hours', isCorrect: true },
              { id: 'b', text: 'Occasional sneezing', isCorrect: false },
              { id: 'c', text: 'Bloody stool or vomit', isCorrect: true },
              { id: 'd', text: 'Difficulty breathing', isCorrect: true },
              { id: 'e', text: 'Slight decrease in activity', isCorrect: false },
              { id: 'f', text: 'Straining to urinate', isCorrect: true },
            ],
            points: 3,
            explanation: 'These symptoms can indicate serious conditions.',
            objectiveId: 'obj_f4_1',
            tags: ['health', 'emergency'],
            difficulty: 'INTERMEDIATE',
          },
        ],
        passingScore: 80,
        allowRetry: true,
        maxAttempts: 3,
        showCorrectAnswers: true,
      },
    },
  ],

  finalAssessment: createAssessment(
    MODULE_IDS.FOSTER_BASICS,
    'Foster Basics Final Assessment',
    20,
    80,
    40
  ),

  estimatedDurationMinutes: 168,
  completionDeadlineDays: 21,
  grantsCertification: true,
  certificationId: 'cert_foster_basics',
  certificationValidityMonths: 24,
  ceCredits: 3,
  ceCategory: 'ROLE_SPECIFIC',
  author: 'PetMayday Training Team',
  reviewedBy: 'Foster Coordinator',
  lastReviewedAt: '2026-01-01T00:00:00Z',
  nextReviewDue: '2027-01-01T00:00:00Z',
  tags: ['foster', 'required', 'care', 'documentation'],
  status: 'ACTIVE',
};

// ═══════════════════════════════════════════════════════════════════
// MODULE REGISTRY
// ═══════════════════════════════════════════════════════════════════

export const TRAINING_MODULES_PART2 = {
  [MODULE_IDS.VOLUNTEER_ORIENTATION]: MODULE_VOLUNTEER_ORIENTATION,
  [MODULE_IDS.TRANSPORT_BASICS]: MODULE_TRANSPORT_BASICS,
  [MODULE_IDS.FOSTER_BASICS]: MODULE_FOSTER_BASICS,
} as const;

export const TRAINING_MODULES = {
  ...TRAINING_MODULES_PART2,
  [MODULE_IDS.MODERATOR_BASICS]: MODULE_MODERATOR_BASICS,
  [MODULE_IDS.CASE_TRIAGE]: MODULE_CASE_TRIAGE,
  [MODULE_IDS.MATCH_VERIFICATION]: MODULE_MATCH_VERIFICATION,
} as const;
