// scripts/sync-env.js
const fs = require('fs');
const path = require('path');

// 1. Define Paths based on your screenshot
// We go up two levels from 'scripts' to reach 'AI Projects', then into 'ADMIN'
const MASTER_REPO_PATH = path.resolve(__dirname, '../../ADMIN');
const MASTER_ENV_FILE = path.join(MASTER_REPO_PATH, '.env.master');
const LOCAL_OVERRIDES_FILE = path.join(__dirname, '../.env.local');
const DESTINATION_FILE = path.join(__dirname, '../.env');

console.log('🔄 Syncing Environment Variables...');
console.log(`   Looking for Master Env at: ${MASTER_ENV_FILE}`);

// 2. Helper to parse ENV files into key-value pairs
function parseEnv(content) {
  const env = {};
  content.split('\n').forEach(line => {
    const cleanLine = line.trim();
    if (cleanLine && !cleanLine.startsWith('#')) {
      const [key, ...valueParts] = cleanLine.split('=');
      if (key) env[key.trim()] = valueParts.join('=').trim();
    }
  });
  return env;
}

try {
  // 3. Load Master Env (Shared Google Cloud, Auth Secrets)
  if (!fs.existsSync(MASTER_ENV_FILE) && !process.env.VERCEL) {
    console.warn(`⚠️  WARNING: Could not find Master ENV at: ${MASTER_ENV_FILE}`);
    console.warn('   Ensure the "ADMIN" folder is a sibling to this project folder.');
  }

  const masterContent = fs.existsSync(MASTER_ENV_FILE)
    ? fs.readFileSync(MASTER_ENV_FILE, 'utf8')
    : '';
  const masterEnv = parseEnv(masterContent);

  // 4. Load Local Overrides (Project-Specific Supabase Keys)
  const localContent = fs.existsSync(LOCAL_OVERRIDES_FILE)
    ? fs.readFileSync(LOCAL_OVERRIDES_FILE, 'utf8')
    : '';
  const localEnv = parseEnv(localContent);

  // 5. Merge: Local overrides Master
  const finalEnvMap = { ...masterEnv, ...localEnv };

  // 6. Format and Write to .env
  const fileHeader = `# AUTOMATICALLY GENERATED by scripts/sync-env.js\n# DO NOT EDIT MANUALLY\n\n`;
  const fileContent = Object.entries(finalEnvMap)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n');

  fs.writeFileSync(DESTINATION_FILE, fileHeader + fileContent);

  console.log(`✅ .env generated successfully!`);
  console.log(`   - Master Source: ADMIN/.env.master (${Object.keys(masterEnv).length} vars)`);
  console.log(`   - Local Overrides: .env.local (${Object.keys(localEnv).length} vars)`);
  console.log(`   - Total Active: ${Object.keys(finalEnvMap).length} variables`);

} catch (error) {
  console.error('❌ Failed to sync env vars:', error);
  process.exit(1);
}
